### ISSUE TITLE
Input Dimension Problem using DVS Dataset

### ISSUE THREAD

**Issue by Po0ria** [nabk89/AutoSNN#1]
Thank you for your interesting work. I have followed the instruction and these are my arguments inside _1_script_train_supernet.sh_:
`#!/bin/bash
gpu=0
dataset_dir='./data'
macro_type=AutoSNN_16
python train_supernet/train.py \
    --gpu $gpu \
    --T 8 --init_tau 2.0 --v_threshold 1.0 --neuron PLIF \
    --epochs 600 \
    --dataset_dir $dataset_dir \
    --dataset_name DVS128Gesture \
    --search_space AutoSNN_16 \
    --macro_type AutoSNN_16 \
    --seed 2022`

Here is the output after executing _1_script_train_supernet.sh_:
`./1_script_train_supernet.sh 
08/18 10:14:08 AM Experiment dir : retrain_result/EXP/AutoSNN_16_DVS128Gesture_Adam_2022_T_8_init_tau_2.0_vth_1.0_neuron_PLIF_split_by_number_normalization_None
08/18 10:14:08 AM saveretrain_result/EXP/AutoSNN_16_DVS128Gesture_Adam_2022_T_8_init_tau_2.0_vth_1.0_neuron_PLIF_split_by_number_normalization_None
08/18 10:14:08 AM report_freq...............................................50
08/18 10:14:08 AM dataset_dir............................................/data
08/18 10:14:08 AM dataset_name...................................DVS128Gesture
08/18 10:14:08 AM gpu........................................................0
08/18 10:14:08 AM seed....................................................2022
08/18 10:14:08 AM resume..................................................None
08/18 10:14:08 AM search_space......................................AutoSNN_16
08/18 10:14:08 AM macro_type........................................AutoSNN_16
08/18 10:14:08 AM epochs...................................................600
08/18 10:14:08 AM batch_size................................................96
08/18 10:14:08 AM optimizer...............................................Adam
08/18 10:14:08 AM learning_rate..........................................0.001
08/18 10:14:08 AM train_portion............................................0.8
08/18 10:14:08 AM T..........................................................8
08/18 10:14:08 AM init_tau.................................................2.0
08/18 10:14:08 AM v_threshold..............................................1.0
08/18 10:14:08 AM neuron..................................................PLIF
08/18 10:14:08 AM split_by..............................................number
08/18 10:14:08 AM normalization...........................................None
08/18 10:14:08 AM cutout.................................................False
08/18 10:14:08 AM cutout_length.............................................16
/afs/crc.nd.edu/user/p/ptaheri/.conda/envs/autoSNN/lib/python3.8/site-packages/torchaudio/backend/utils.py:53: UserWarning: "sox" backend is being deprecated. The default backend will be changed to "sox_io" backend in 0.8.0 and "sox" backend will be removed in 0.9.0. Please migrate to "sox_io" backend. Please refer to https://github.com/pytorch/audio/issues/903 for the detail.
  warnings.warn(
npy format events data root ./data/DVS128Gesture/events_npy/train, ./data/DVS128Gesture/events_npy/test already exists
frames data root ./data/DVS128Gesture/frames_num_8_split_by_number_normalization_None already exists.
npy format events data root ./data/DVS128Gesture/events_npy/train, ./data/DVS128Gesture/events_npy/test already exists
frames data root ./data/DVS128Gesture/frames_num_8_split_by_number_normalization_None already exists.
08/18 10:14:08 AM D_train: 864, D_val: 216
08/18 10:14:13 AM D_train: [72, 73, 72, 76, 74, 73, 73, 143, 70, 70, 68]
08/18 10:14:13 AM D_val: [17, 17, 18, 14, 16, 17, 18, 37, 20, 20, 22]
08/18 10:14:13 AM When training the super-network, D_val is not used; When searching, D_train is not used.
08/18 10:14:13 AM stem conv 3x3	128 x 128 x 3	-->	128 x 128 x 16
08/18 10:14:13 AM ------- additional stem layers for DVS data -------
08/18 10:14:13 AM max_pool_k2	128 x 128 x 16	-->	64 x 64 x 16
08/18 10:14:13 AM conv_k3   	64 x 64 x 16	-->	64 x 64 x 16
08/18 10:14:13 AM max_pool_k2	64 x 64 x 16	-->	32 x 32 x 16
08/18 10:14:13 AM ----------------- TBD block layers -----------------
08/18 10:14:13 AM TBD (normal)	32 x 32 x 16	-->	32 x 32 x 16
08/18 10:14:13 AM max_pool_k2	32 x 32 x 16	-->	16 x 16 x 16
08/18 10:14:13 AM TBD (normal)	16 x 16 x 16	-->	16 x 16 x 32
08/18 10:14:13 AM TBD (normal)	16 x 16 x 32	-->	16 x 16 x 32
08/18 10:14:13 AM max_pool_k2	16 x 16 x 32	-->	8 x 8 x 32
08/18 10:14:13 AM TBD (normal)	8 x 8 x 32	-->	8 x 8 x 64
08/18 10:14:13 AM TBD (normal)	8 x 8 x 64	-->	8 x 8 x 64
08/18 10:14:13 AM max_pool_k2	8 x 8 x 64	-->	4 x 4 x 64
08/18 10:14:13 AM ----------------------------------------------------
08/18 10:14:13 AM Spike FC	1024	-->	110
08/18 10:14:13 AM boost   	110	-->	11
08/18 10:14:13 AM epoch 0
Traceback (most recent call last):
  File "train_supernet/train.py", line 203, in <module>
    run()
  File "train_supernet/train.py", line 140, in run
    train_acc, avg_num_spikes, train_obj = train(train_loader, net, optimizer, args, criterion)
  File "train_supernet/train.py", line 174, in train
    out_spikes_counter, num_of_spikes, block_ids = net(input)
  File "/afs/crc.nd.edu/user/p/ptaheri/.conda/envs/autoSNN/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/afs/crc.nd.edu/user/p/ptaheri/Private/benchmarkSNN/AutoSNN/./train_supernet/supernet.py", line 169, in forward
    x = self.conv_stem(x)
  File "/afs/crc.nd.edu/user/p/ptaheri/.conda/envs/autoSNN/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/afs/crc.nd.edu/user/p/ptaheri/.conda/envs/autoSNN/lib/python3.8/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/afs/crc.nd.edu/user/p/ptaheri/.conda/envs/autoSNN/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/afs/crc.nd.edu/user/p/ptaheri/.conda/envs/autoSNN/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 423, in forward
    return self._conv_forward(input, self.weight)
  File "/afs/crc.nd.edu/user/p/ptaheri/.conda/envs/autoSNN/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 419, in _conv_forward
    return F.conv2d(input, weight, self.bias, self.stride,`
**RuntimeError: Expected 4-dimensional input for 4-dimensional weight [16, 2, 3, 3], but got 5-dimensional input of size [96, 8, 2, 128, 128] instead**

By the way, it works for CIFAR dataset.

**Comment by nabk89** [comment]
Thank you for your interest, and sorry for delaying the answer (due to my vacation ^^;;).

The problem is caused by "forward()" function in SpikingNetwork class defined in the "supernet.py".
Uploading the current file was my mistake, and I'll re-upload the fixed file ASAP.

For now, you can fix "forward() function in supernet.py" according to "forward() function in retrain/childnet.py (lines 162~191)". 
Thank you!

**Comment by Po0ria** [comment]
I modified it and fixed it. Thank you!
I can not reproduce the results from paper for DVS Gesture dataset. I was wondering if you could provide the parameters that you used?

**Comment by Po0ria** [comment]
And also default Vth = 1.0 and not 0. right?
![image](https://user-images.githubusercontent.com/8793280/188710253-b3053cf3-d246-4ed0-96ef-9e428613c778.png)

**Comment by nabk89** [comment]
Oh.. Thank you for this typo. Yes, as you understand, we set Vth = 1.0 in the all experiments.

**Comment by Po0ria** [comment]
I appreciate your reply. I am trying to reproduce your results for DVS Gesture and here are my parameters:
**1_script_train_supernet.sh:** 
```
#!/bin/bash
gpu=0
dataset_dir='./data'
macro_type=AutoSNN_16
python train_supernet/train.py \
    --gpu $gpu \
    --T 8 --init_tau 2.0 --v_threshold 1.0 --neuron PLIF \
    --epochs 600 \
    --dataset_dir $dataset_dir \
    --dataset_name DVS128Gesture \
    --search_space AutoSNN_16 \
    --macro_type AutoSNN_16 \
    --seed 2022
```
**2_script_search.sh:** 
```
#!/bin/bash

gpu=0
dataset_dir='./data'

#search_mode=random ## WS + random search (in Table 5)
search_mode=evolution ## AutoSNN

## This super-network will be generated after executing 1_script_train_supernet.sh
trained_supernet='retrain_result/EXP/AutoSNN_16_DVS128Gesture_Adam_2022_T_8_init_tau_2.0_vth_1.0_neuron_PLIF_split_by_number_normalization_None/checkpoint.pth.tar'

python search_arch/search.py \
    --gpu $gpu \
    --T 8 --init_tau 2.0 --v_threshold 1.0 --neuron PLIF \
    --dataset_dir $dataset_dir \
    --dataset_name DVS128Gesture \
    --supernet $trained_supernet \
    --seed 2022 \
    --search_space AutoSNN_16 \
    --search_algo $search_mode \
    --fitness ACC_pow_spikes \
    --fitness_lambda -0.08 \
    --avg_num_spikes 400000
```
I changed 'avg_num_spikes' from 110K to 400K based on table 4 in the paper:

<img width="635" alt="Screen Shot 2022-09-08 at 11 10 49 AM" src="https://user-images.githubusercontent.com/8793280/189159022-126c187c-e309-433c-b039-2823dee8ed53.png" width=100>

**3_script_retrain.sh:**
```
arch=AutoSNN
macro_type=AutoSNN_16
python retrain/train.py \
    --gpu $gpu \
    --T 8 --init_tau 2.0 --v_threshold 1.0 --neuron PLIF \
    --epochs 600 \
    --dataset_dir $dataset_dir \
    --dataset_name DVS128Gesture \
    --save $arch \
    --arch $arch \
    --macro_type $macro_type \
    --seed 2022
```

Here is the retrain log for the final model:
```
2022-09-06 16:06:55,394 Experiment dir : retrain_result/AutoSNN/AutoSNN_16_DVS128Gesture_Adam_2022_T_8_init_tau_2.0_vth_1.0_neuron_PLIF_split_by_number_normalization_None_cutout_False
2022-09-06 16:06:55,395 saveretrain_result/AutoSNN/AutoSNN_16_DVS128Gesture_Adam_2022_T_8_init_tau_2.0_vth_1.0_neuron_PLIF_split_by_number_normalization_None_cutout_False
2022-09-06 16:06:55,395 report_freq...............................................50
2022-09-06 16:06:55,395 conventional_arch.......................................None
2022-09-06 16:06:55,395 conventional_init_channels...............................128
2022-09-06 16:06:55,395 macro_type........................................AutoSNN_16
2022-09-06 16:06:55,395 arch.................................................AutoSNN
2022-09-06 16:06:55,395 dataset_dir............................................/data
2022-09-06 16:06:55,395 dataset_name...................................DVS128Gesture
2022-09-06 16:06:55,395 gpu........................................................0
2022-09-06 16:06:55,395 seed....................................................2022
2022-09-06 16:06:55,396 resume..................................................None
2022-09-06 16:06:55,396 epochs...................................................600
2022-09-06 16:06:55,396 batch_size................................................96
2022-09-06 16:06:55,396 optimizer...............................................Adam
2022-09-06 16:06:55,396 learning_rate..........................................0.001
2022-09-06 16:06:55,396 T..........................................................8
2022-09-06 16:06:55,396 init_tau.................................................2.0
2022-09-06 16:06:55,396 v_threshold..............................................1.0
2022-09-06 16:06:55,396 neuron..................................................PLIF
2022-09-06 16:06:55,396 split_by..............................................number
2022-09-06 16:06:55,397 normalization...........................................None
2022-09-06 16:06:55,397 cutout.................................................False
2022-09-06 16:06:55,397 cutout_length.............................................16
2022-09-06 16:06:55,562 stem conv 3x3   128 x 128 x 2   --> 128 x 128 x 16
2022-09-06 16:06:55,562 ------- additional stem layers for DVS data -------
2022-09-06 16:06:55,563 max_pool_k2 128 x 128 x 16  --> 64 x 64 x 16
2022-09-06 16:06:55,563 conv_k3     64 x 64 x 16    --> 64 x 64 x 16
2022-09-06 16:06:55,926 max_pool_k2 64 x 64 x 16    --> 32 x 32 x 16
2022-09-06 16:06:55,926 ------------------- block layers -------------------
2022-09-06 16:06:55,926 SRB_k5  32 x 32 x 16    --> 32 x 32 x 16
2022-09-06 16:06:55,926 max_pool_k2 32 x 32 x 16    --> 16 x 16 x 16
2022-09-06 16:06:55,927 SRB_k5  16 x 16 x 16    --> 16 x 16 x 32
2022-09-06 16:06:55,927 skip_connect    16 x 16 x 32    --> 16 x 16 x 32
2022-09-06 16:06:55,928 max_pool_k2 16 x 16 x 32    --> 8 x 8 x 32
2022-09-06 16:06:55,928 SRB_k3  8 x 8 x 32  --> 8 x 8 x 64
2022-09-06 16:06:55,929 SRB_k5  8 x 8 x 64  --> 8 x 8 x 64
2022-09-06 16:06:55,930 max_pool_k2 8 x 8 x 64  --> 4 x 4 x 64
2022-09-06 16:06:55,930 ----------------------------------------------------
2022-09-06 16:06:55,931 Spike FC    1024    --> 110
2022-09-06 16:06:55,931 boost       110 --> 11
```
And the last line of the log (600 epochs):
```
2022-09-06 16:59:42,190 epoch 599
2022-09-06 16:59:43,062 train (000/12) loss: 1.035748e-04 top1: 1.000000 batchtime: 0.31 sec
2022-09-06 16:59:45,856 train (011/12) loss: 6.543298e-05 top1: 1.000000 batchtime: 0.26 sec
2022-09-06 16:59:45,956 train_acc 1.000000 train_avg_spikes 171570
2022-09-06 16:59:47,108 valid (000/1) top1: 0.885417
2022-09-06 16:59:47,175 valid_acc 0.885417 val_avg_spikes 173829 best_acc 0.916667 best_acc_spikes 113848 (at epoch 325)
2022-09-06 16:59:47,230 epoch time: 5 sec.
```
My best accuracy is **_91.67%_**

**Comment by nabk89** [comment]
Table 4 shows the results of my architecture that was searched by using CIFAR10 and avg_num_spikes=110K.
The searched architecture is illustrated by Figure 11-(b) (in the appendix).
Please compare with your searched architecture.
In my guess, your architecture may have more skip layers.

**Comment by Po0ria** [comment]
I guess I don't understand. Table 4 shows your architectures on different datasets from the look of it. Am I wrong? 
And it does specify the search space, accuracy, and average number of spikes for each

**Comment by nabk89** [comment]
We explained about Table 4 in 8 page (just below Table 4). 
In the sentence "We further evaluate our searched SNN architecture by transferring it to various datasets" in the paragraph, "our searched SNN architecture" is the architecture that was searched by using CIFAR10 and is illustrated by Figure 11-(b) as I said.
In other words, Table 4 includes the performance of the searched architecture on different datasets.
Such evaluation is used to demonstrate the generalizability (or transferrability) of the searched architecture and can be generally found in NAS papers.

If you want to find a new architecture on DVS128-Gesture, I recommend you set avg_num_spikes as the averaged number of spikes according to your supernet training log file (not 423K).
Note that 423K in Table 4 means the number of spikes of our architecture (searched by CIFAR10) on DVS128-Gesture test set after training it using DVS128-Gesture training set.
Also, tuning the hyperparameter lambda may be required.

**Comment by Po0ria** [comment]
Thank you for the clarification.

**Comment by 3551574912** [comment]
i just run 1_script_train_supernet.sh , then i got this result,the avg_num_spikes is 0 all the time ,and  i did not change any code , do i need to run 2_script_train_supernet.sh and 2_script_train_supernet.sh ;then the avg_num_spikes will be the same as yours?

![Image](https://github.com/user-attachments/assets/8aba7727-2f2b-4b39-93f0-52cccb9df7d7)
